Draft : Feat/mongodb
viridIT/vSMTP pull request #1034
Opened 2023-02-22 01:38 UTC by jeangd

## Requirements

- [ ] I have read the `CODE_OF_CONDUCT.md`.
- [ ] I have updated `CHANGELOG.md` & `tools/install/deb/changelog` to reflect my changes.

## Motivation

## Solution

2023-02-22 13:53 UTC, ltabis requested changes
Please check the comments.

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/.gitignore
> +# Generated by Cargo
Please remove this file.

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/.cargo/Cargo.toml
> +[env]
Please remove this file.

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/README.md
> +# vsmtp-plugin-redis
Please remove this file or add usage examples.

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/src/api.rs
> +    // pub fn drop_index(&self, index: rhai::Dynamic, options: rhai::Dynamic) -> std::result::Result<(), Box<rhai::EvalAltResult>> {
Why is this commented ?

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/src/api.rs
> +    #[rhai_fn(global, pure)]
What is the purpose of this function ?

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/src/api.rs
> +    pub fn create_index(
The comments of this functions relates to `insert_one`, not `create_index`

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/src/api.rs
> +        options: rhai::Dynamic
Options are never used in your connector implementation, this could confuse the user.
I think it would be better if you removed this argument.

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/src/api.rs
> +        match dbg!(result).unwrap() {
All `dbg!` should be removed.

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/src/api.rs
> +            Some(doc) => Ok(rhai::Dynamic::UNIT),
This function always returns a UNIT ?

2023-02-22 13:53 UTC, ltabis commented on src/plugins/vsmtp-plugin-mongodb/src/api.rs
> +    /// export const result = mongo::find_one_and_update(collection, #{}, #{}, #{});
Your examples do not really show how to use your functions, you should at least add the parameters to your `Map` argument.

2023-04-05 06:40 UTC, Mathieu-Lala approved these changes

2023-04-05 11:37 UTC, ltabis approved these changes

2023-04-05 11:38 UTC, merged