Added dotenv support and tests
viridIT/vSMTP pull request #1039
Opened 2023-02-25 22:02 UTC by fa993

## Requirements

- [ x] I have read the `CODE_OF_CONDUCT.md`.
- [ x] I have updated `CHANGELOG.md` & `tools/install/deb/changelog` to reflect my changes.

## Motivation

Addresses #1035 

## Solution

```markdown
### Added
- Added dotenv crate
- Added passing env file in the command line
```

2023-03-03 18:20 UTC, Mathieu-Lala commented
I opened a PR on your repo @fa993 , once your merged it in your `develop`, we can merge your `develop` in vSMTP

2023-03-04 02:34 UTC, fa993 commented
> I opened a PR on your repo @fa993 , once your merged it in your `develop`, we can merge your `develop` in vSMTP.
> [fa993#1](https://github.com/fa993/vSMTP/pull/1)

@Mathieu-Lala I merged your PR

2023-03-04 11:26 UTC, Mathieu-Lala commented
There is just a conflict in the `Cargo.toml`, take both dotenv and the latest version of `clap`

2023-03-04 11:44 UTC, fa993 commented
> There is just a conflict in the `Cargo.toml`, take both dotenv and the latest version of `clap`

@Mathieu-Lala I updated the version of clap, not sure how to resolve the dotenv conflict

2023-03-04 11:49 UTC, Mathieu-Lala commented
You can just remove those lines
```
<<<<<<< develop
=======
>>>>>>> develop
```

2023-03-04 12:01 UTC, Mathieu-Lala approved these changes

2023-03-04 13:05 UTC, Mathieu-Lala requested changes
To make the CI pass

2023-03-04 13:05 UTC, Mathieu-Lala commented on src/vsmtp/vsmtp-test/src/tests/mod.rs
> +    mod dotenv;
Format like this:
```rs
  mod dotenv;
  mod quarantine;
```

2023-03-04 13:05 UTC, Mathieu-Lala commented on src/vsmtp/vsmtp-core/src/args.rs
> +                config: "path".to_string(),
Fix the test with:
```rs
  config: "/etc/vsmtp/vsmtp.vsl".to_string()
```

2023-03-04 17:03 UTC, Mathieu-Lala approved these changes

2023-03-04 17:03 UTC, Mathieu-Lala commented
Good to go, thank you for your contribution to vSMTP ! 🚀

2023-03-04 17:05 UTC, merged

2023-03-05 03:18 UTC, fa993 commented
Your welcome!