Fix default virtual server
viridIT/vSMTP pull request #1078
Opened 2023-03-16 06:45 UTC by Mathieu-Lala

# Summary of changes

## Removed

* the `is_default` properties in the `on_domain_config()`
* the assignation of a default vritual server using a symlink named `default`

## Added

* `config.server.tls.certificate` & `config.server.tls.certificate` (optional) used when a SNI is not provided or not found among the virtuals server

2023-03-16 07:49 UTC, paguardiolle approved these changes

2023-03-16 07:49 UTC, paguardiolle commented on src/vsmtp/vsmtp-config/src/config.rs
> +        pub default: Option<FieldServerVirtualTls>,
Ca il faut impérativement l'ajouter dans la doc...

2023-03-16 10:18 UTC, ltabis approved these changes

2023-03-16 15:45 UTC, ltabis requested changes
Changelogs are not up to date !

2023-03-17 10:02 UTC, ltabis approved these changes

2023-03-17 10:09 UTC, paguardiolle commented on CHANGELOG.md
> +* `config.server.tls.certificate` & `config.server.tls.certificate` (optional) used when a SNI is not provided or not found among the virtuals server
config.server.tls.certificate & config.server.tls.certificate ???

2023-03-17 10:17 UTC, ltabis approved these changes

2023-03-17 11:01 UTC, merged