activate smtputf8 only if 8bitemime is enable
viridIT/vSMTP pull request #1188
Opened 2023-05-16 13:32 UTC by LangArthur

## Requirements

- [x] I have read the `CODE_OF_CONDUCT.md`.
- [x] I have updated `CHANGELOG.md` & `tools/install/deb/changelog` to reflect my changes.

## Motivation

It was possible to enable smtputf8 without 8bitsmime, which is not allowed by rfc 6531.

2023-05-22 07:07 UTC, ltabis approved these changes

2023-05-22 19:36 UTC, ltabis requested changes
A minor code quality fix to do

2023-05-22 19:36 UTC, ltabis commented on src/vsmtp/vsmtp-protocol/src/command.rs
> +                                                .get(..i.len())
If you are sure there aren't going to be any overflow, use the `array[x]` syntax instead of `get`

2023-05-23 06:37 UTC, LangArthur commented on src/vsmtp/vsmtp-protocol/src/command.rs
> +                                                .get(..i.len())
Since it is not my code, I am not sure about it

2023-05-23 13:37 UTC, merged