Feat/sqlite
viridIT/vSMTP pull request #1197
Opened 2023-05-29 05:27 UTC by Yzorek

## Requirements

- [ ] I have read the `CODE_OF_CONDUCT.md`.
- [ ] I have updated `CHANGELOG.md` & `tools/install/deb/changelog` to reflect my changes.

## Motivation

## Solution

2023-06-01 15:25 UTC, Mathieu-Lala requested changes

2023-06-01 15:25 UTC, Mathieu-Lala commented on src/plugins/vsmtp-plugin-sqlite/src/lib.rs
> +
Add the clippy lints

2023-06-01 15:25 UTC, Mathieu-Lala commented on src/plugins/vsmtp-plugin-sqlite/Cargo.toml
> +smartstring = { version = "*", features = ["proptest", "serde"] }
Set a full version for `smartstring` and why is there `proptest` ?

2023-06-01 15:25 UTC, Mathieu-Lala commented on src/plugins/vsmtp-plugin-sqlite/Cargo.toml
> +smartstring = { version = "*", features = ["proptest", "serde"] }
Set a full version for `smartstring` and why is there `proptest` ?

2023-06-01 17:28 UTC, ltabis commented on src/plugins/vsmtp-plugin-sqlite/src/lib.rs
> +
which one ?

2023-06-01 18:00 UTC, Mathieu-Lala commented on src/plugins/vsmtp-plugin-sqlite/src/lib.rs
> +
All of them :)

2023-09-05 09:50 UTC, closed without merging

2023-09-05 09:50 UTC, ltabis commented
Closing this since we release vSMTP v3.