feat/chunking
viridIT/vSMTP pull request #1211
Opened 2023-06-07 15:17 UTC by Flo-Pc

## Requirements

- [x] I have read the `CODE_OF_CONDUCT.md`.
- [x] I have updated `CHANGELOG.md` & `tools/install/deb/changelog` to reflect my changes.

## Motivation

vSMTP was not compatible with the chunking feature as described in RFC #3030

## Solution

### Added
- Added chunking support, including BDAT command support

2023-06-13 15:41 UTC, Mathieu-Lala commented on src/vsmtp/vsmtp-protocol/src/reader.rs
> +                if self.buffer.starts_with(b"BDAT ") {
Something feels wrong

2023-06-13 15:44 UTC, Mathieu-Lala commented on src/vsmtp/vsmtp-test/src/tests/protocol/bdat.rs
> +
Add more tests without `pipelining`, and add assert on the content of the message received

2023-06-20 13:16 UTC, Mathieu-Lala requested changes

2023-06-20 13:16 UTC, Mathieu-Lala commented on src/vsmtp/vsmtp-protocol/src/command.rs
> +        let size = args_part.trim().parse::<usize>().unwrap_or(0);
Should produce `InvalidArgs` error

2023-09-05 09:49 UTC, ltabis commented
Closing this since we release vSMTP v3.

2023-09-05 09:49 UTC, closed without merging