feat<config>: replace string=>pathbuf for path & add whitelist (log)
viridIT/vSMTP pull request #139
Opened 2022-02-10 13:37 UTC by Mathieu-Lala

2022-02-10 13:51 UTC, ltabis approved these changes

2022-02-11 09:27 UTC, ltabis submitted a review, later dismissed

2022-02-11 11:13 UTC, paguardiolle requested changes
Pas de whitelist...

2022-02-14 12:43 UTC, ltabis approved these changes

2022-02-14 13:28 UTC, paguardiolle approved these changes

2022-02-14 13:28 UTC, merged