Enhance deliveries error
viridIT/vSMTP pull request #1392
Opened 2023-10-13 16:22 UTC by Mathieu-Lala

2023-10-30 09:13 UTC, LangArthur requested changes

2023-10-30 09:13 UTC, LangArthur commented on crates/delivery/src/smtp/exchange.rs
> +            at_least_one_rcpt_is_valid |= handler
I am not sure to understand the logic :
If at least one rcpt is valid, no error should be raised ? What happens to the remaining rcpt ?

2023-10-30 10:23 UTC, Mathieu-Lala commented on crates/common/src/delivery_attempt/mod.rs
> +    inner: DeliveryType,
It is a private member, so it is not an api changes, but for a shorter json serialization.

2023-10-30 10:24 UTC, Mathieu-Lala commented on crates/delivery/src/bin/basic.rs
> +            std::net::SocketAddr::new(ip, 25),
Always has been.

2023-10-30 10:30 UTC, Mathieu-Lala commented on crates/delivery/src/smtp/exchange.rs
> +            at_least_one_rcpt_is_valid |= handler
The logic is: if all the RCPT TO failed, the DATA command should not be sent.

2023-11-03 09:45 UTC, ltabis commented on crates/delivery/src/send.rs
> +        sni: server_name.try_into().unwrap(),
Since the server_name parameter is of type `Domain` it should always be valid when transformed into an SNI, hence the unwrap

2023-11-03 09:57 UTC, ltabis commented on crates/delivery/src/send.rs
> +        return dbg!(sender.handler().take_result());
Shouldn't this be logged with tracing instead of dbg! ?

2023-11-03 09:59 UTC, ltabis commented on crates/delivery/src/smtp/exchange.rs
> +        if handler.on_data_end(data_end_reply).await == Err(()) {
I guess this if statement is not needed since l.174 and l.177 do the same thing

2023-11-03 10:00 UTC, ltabis commented on crates/delivery/src/smtp/exchange.rs
> +        if handler.on_data_end(data_end_reply).await == Err(()) {
You could just
```rust
handler.on_data_end(data_end_reply).await;
handler.take_result()
```

Is it because clippy would tell you to use the result otherwise ?

2023-11-03 10:06 UTC, ltabis commented on crates/receiver/src/smtp/rules/api.rs
> +    pub const fn panic() {
if this is used to debug purposes please add a `#[cfg(debug_assertion)]` attribute here.

2023-11-03 10:10 UTC, ltabis reviewed
Check out the comments

2023-11-03 10:46 UTC, ltabis approved these changes

2023-11-03 10:47 UTC, merged