Logs future
viridIT/vSMTP pull request #1419
Opened 2023-10-26 11:52 UTC by ltabis

## Requirements

- [x] I have read the `CODE_OF_CONDUCT.md`.
~~I have updated `CHANGELOG.md` & `tools/install/deb/changelog` to reflect my changes.~~
~~I have written/updated documentation (if applicable) for the changes I propose.~~

## Documentation

None

## Motivation

A dependency would crash services because it would call `tracing::trace` while not in a tokio reactor.

## Solution

### Changed

- Re-introduce a future to send logs and fixed the missing message issue at the same time.

2023-10-27 07:21 UTC, LangArthur requested changes

2023-10-27 07:21 UTC, LangArthur commented on crates/tracing-amqp/src/lib.rs
> -            hostname: hostname::get().map_or(None, |hostname| hostname.into_string().ok()),
according to rfcs 5424, hostname must be the machine hostname (or ip if not found), so we should not replace it by something else

2023-10-30 14:09 UTC, Mathieu-Lala approved these changes

2023-10-30 14:16 UTC, Mathieu-Lala approved these changes

2023-10-30 14:35 UTC, merged