lint: deny unsafe code & setup dependabot
viridIT/vSMTP pull request #232
Opened 2022-04-14 21:33 UTC by Mathieu-Lala

2022-04-15 09:09 UTC, ltabis requested changes

2022-04-15 09:09 UTC, ltabis commented on vsmtp-common/src/lib.rs
> +#![deny(unsafe_code)]
What's the point ?

2022-04-15 09:11 UTC, Mathieu-Lala commented on vsmtp-common/src/lib.rs
> +#![deny(unsafe_code)]
Explicit our no unsafe policy unless required

2022-04-15 09:13 UTC, ltabis commented on vsmtp-common/src/lib.rs
> +#![deny(unsafe_code)]
I think it's useless

2022-04-17 11:37 UTC, ltabis requested changes
remove `#![deny(unsafe_code)]`

2022-04-18 04:07 UTC, closed without merging