Integration of Auth in vSMTP config
viridIT/vSMTP pull request #263
Opened 2022-04-23 07:58 UTC by Mathieu-Lala

2022-04-24 03:26 UTC, Mathieu-Lala commented
Related to #150

2022-04-24 08:36 UTC, paguardiolle commented on examples/config/auth.toml
> +must_be_authenticated = true
Je n'aime pas le "wording" de ces deux champs.

Si on cherche une cohérence p/r aux autres tables on devrait avoir des trucs du genre:
security_level = encrypt | may | ...

Il ne manque pas un "protocol = sasl | ..." ??

Pour l'instant on laisse. A discuter.

2022-04-24 08:36 UTC, paguardiolle commented on vsmtp-common/src/mail_context.rs
> +pub enum AuthCredentials {
Pour mon info je ne comprends pas à quoi sert cette enum...

2022-04-24 08:36 UTC, paguardiolle commented on vsmtp-common/src/status.rs
> +    /// data has being send from the rule engine to the server
Idem. Je ne comprends pas. Pourquoi un état send ? on attend un retour ???

2022-04-24 08:36 UTC, paguardiolle commented on vsmtp-rule-engine/src/modules/mail_context.rs
> +    #[rhai_fn(global, get = "type", pure)]
kesako ?

2022-04-24 08:36 UTC, paguardiolle commented on vsmtp-server/src/receiver/mod.rs
> +    match on_authentication(conn, rsasl, rule_engine, mechanism, initial_response).await {
J'ai pas fait gaffe... ya un timeout si ca répond pas ?

2022-04-24 08:36 UTC, paguardiolle commented on vsmtp-test/src/tests/auth.vsl
> +#{
c clairement hardcore...

2022-04-24 08:36 UTC, paguardiolle commented on vsmtp-test/src/tests/auth.vsl
> +            switch ctx.auth.type {
je commence à comprendre... je remonte dans le code...

2022-04-24 08:36 UTC, paguardiolle commented on vsmtp-test/src/tests/auth.vsl
> +            switch ctx.auth.type {
Ok... 
Y a donc deux étapes dans vsl ?? l'envoi vers un backend de connexion et le retour qui permet d'accept/deny.
Si c ça je comprends mieux l'intérêt d'un service "saslauthd" accessible depuis la rule engine.

Why not. A discuter - et certainement à "enjoliver/wrapper" (cf. remarques sur cohérence toml) idem ici.

2022-04-24 09:15 UTC, ltabis commented on vsmtp-rule-engine/src/modules/mail_context.rs
> +    #[rhai_fn(global, get = "type", pure)]
c'est pour faire `ctx.auth.type`

2022-04-24 09:37 UTC, ltabis requested changes

2022-04-24 09:37 UTC, ltabis commented on vsmtp-server/src/auth.rs
> +        let mut rule_state = RuleState::new(&config);
The previous state is lost here.

2022-04-24 09:37 UTC, ltabis commented on vsmtp-server/src/auth.rs
> +            rsasl::Property::GSASL_VALIDATE_SIMPLE if result == Status::Accept => Ok(()),
To specify in the documentation, `Accept` required.

2022-04-24 09:37 UTC, ltabis commented on vsmtp-server/src/receiver/mod.rs
> +    match on_authentication(conn, rsasl, rule_engine, mechanism, initial_response).await {
Pas sur l'entièreté de l'authentification, mais sur la réponse du client oui (défaut 1 seconde)

2022-04-25 08:51 UTC, ltabis approved these changes

2022-04-25 11:19 UTC, ltabis commented on vsmtp-server/src/auth.rs
> +        let mut rule_state = RuleState::new(&config);
To fix in a futur pr !

2022-04-25 11:19 UTC, merged