Support DKIM
viridIT/vSMTP pull request #397
Opened 2022-06-23 09:54 UTC by Mathieu-Lala

2022-07-03 14:06 UTC, Mathieu-Lala commented on src/vsmtp/vsmtp-common/src/message/mail.rs
> +            .replace("Id", "ID")
Remove that

2022-07-11 16:16 UTC, ltabis commented on src/vsmtp/vsmtp-mail-parser/src/helpers.rs
>  pub fn remove_comments(line: &str) -> anyhow::Result<String> {
Watch out for function that parses headers, they must take comments into account.

2022-07-11 16:33 UTC, ltabis submitted a review, later dismissed

2022-07-18 11:14 UTC, ltabis requested changes

2022-07-18 11:14 UTC, ltabis commented on src/vsmtp/vsmtp-dkim/Cargo.toml
> +vsmtp-common = { path = "../vsmtp-common", version = "1.1.0", default-features = false }
bump to 1.1.3 ? + `package.metadata.release` section ?

2022-07-18 11:31 UTC, ltabis approved these changes

2022-07-18 12:56 UTC, ltabis approved these changes

2022-07-18 12:57 UTC, merged