Support DMARC (2)
viridIT/vSMTP pull request #506
Opened 2022-08-16 13:53 UTC by Mathieu-Lala

# Context

see #464 

# Summary of changes

## Fixed

* initialize the log before the drop of privilege
* fix log format of syslog & files & stdout (with several layers)
* English typos

## Added

* `check_dmarc` function in vsl's api
* implementation of dmarc checks until application of the policy (and not further)

2022-08-22 14:32 UTC, ltabis commented on src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
> +    pub fn parse_rfc5322_from(message: Message) -> EngineResult<Address> {
you could add `&mut` in the front of `Message` to prevent an `Arc` copy.

2022-08-22 14:39 UTC, ltabis requested changes

2022-08-22 14:39 UTC, ltabis commented on src/vsmtp/vsmtp-rule-engine/src/api/types.rs
> +    pub fn domain_address(addr: &mut Address) -> String {
All email addresses are wrapped into the `SharedObject` struct, this function is not needed.

2022-08-22 14:39 UTC, ltabis commented on src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
> +    pub fn get_root_domain(domain: &str) -> String {
This function could also be applied on `SharedObject::Address`

2022-08-22 16:40 UTC, Mathieu-Lala commented on src/vsmtp/vsmtp-rule-engine/src/api/types.rs
> +    pub fn domain_address(addr: &mut Address) -> String {
Should a change the output of `parse_rfc5322_from` to return a `SharedObject` ?

2022-08-22 19:12 UTC, ltabis commented on src/vsmtp/vsmtp-rule-engine/src/api/types.rs
> +    pub fn domain_address(addr: &mut Address) -> String {
yes!

2022-08-23 11:21 UTC, ltabis submitted a review, later dismissed

2022-08-23 12:05 UTC, ltabis submitted a review, later dismissed

2022-08-24 09:09 UTC, ltabis commented on src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
> +    #[allow(clippy::needless_pass_by_value)]
This can now be removed.

2022-08-24 09:16 UTC, ltabis approved these changes

2022-08-24 09:17 UTC, merged