Docs
viridIT/vSMTP pull request #520
Opened 2022-08-23 15:39 UTC by ltabis

Minor docs enhancements.

2022-08-23 16:55 UTC, Mathieu-Lala requested changes

2022-08-23 16:55 UTC, Mathieu-Lala commented on src/vsmtp/vsmtp-rule-engine/api/message.rhai
> +/// All of them. Even tough the email is not received at the current stage,
`Even though` (in all the file)

2022-08-24 09:25 UTC, ltabis commented on src/vsmtp/vsmtp-rule-engine/api/message.rhai
> +/// All of them. Even tough the email is not received at the current stage,
fixed in [7e054e8](https://github.com/viridIT/vSMTP/pull/520/commits/7e054e8c03418aaa45dc057b04eefba579243f1e)

2022-08-24 09:47 UTC, Mathieu-Lala approved these changes

2022-08-24 10:00 UTC, merged