vMIME process
viridIT/vSMTP pull request #74
Opened 2022-01-11 18:47 UTC by Mathieu-Lala

2022-01-11 18:50 UTC, Mathieu-Lala commented on src/resolver/deliver_queue.rs
> +        let dir = parent.into().join(self.as_str().to_string() + "/");
remove .to_string() + "/"

2022-01-11 19:16 UTC, ltabis requested changes

2022-01-11 19:16 UTC, ltabis commented on src/main.rs
> -    // and initialize the rule engine's rule directory.
Don't remove comments please

2022-01-11 19:16 UTC, ltabis commented on src/resolver/deliver_queue.rs
> +    sender: crossbeam_channel::Sender<String>,
Why did you changed the name ?

2022-01-11 20:45 UTC, Mathieu-Lala commented on src/resolver/deliver_queue.rs
> +    sender: crossbeam_channel::Sender<String>,
It is not deliver_proc but working_proc. Just sender is more simple

2022-01-12 07:41 UTC, ltabis approved these changes

2022-01-12 07:48 UTC, merged